//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Order_Line = new HashSet<Order_Line>();
            this.Patrol_Asset = new HashSet<Patrol_Asset>();
        }
    
        public int Asset_ID { get; set; }
        public string Description { get; set; }
        public int Asset_Status_ID { get; set; }
        public Nullable<int> Asset_Type_ID { get; set; }
    
        public virtual Asset_Status Asset_Status { get; set; }
        public virtual Asset_Type Asset_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Line> Order_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patrol_Asset> Patrol_Asset { get; set; }
    }
}
