//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INF370Entities : DbContext
    {
        public INF370Entities()
            : base("name=INF370Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access_Level> Access_Level { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<Asset_Status> Asset_Status { get; set; }
        public virtual DbSet<Asset_Type> Asset_Type { get; set; }
        public virtual DbSet<Cellphone> Cellphones { get; set; }
        public virtual DbSet<Event_Reward> Event_Reward { get; set; }
        public virtual DbSet<Event_Type> Event_Type { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Gate> Gates { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<Incident_Level> Incident_Level { get; set; }
        public virtual DbSet<Incident_Status> Incident_Status { get; set; }
        public virtual DbSet<Incident_Type> Incident_Type { get; set; }
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<Marker> Markers { get; set; }
        public virtual DbSet<Marker_Type> Marker_Type { get; set; }
        public virtual DbSet<Medical_Aid> Medical_Aid { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_Line> Order_Line { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<Patrol_Booking> Patrol_Booking { get; set; }
        public virtual DbSet<Patrol_Log> Patrol_Log { get; set; }
        public virtual DbSet<Product_Reward> Product_Reward { get; set; }
        public virtual DbSet<Product_Type> Product_Type { get; set; }
        public virtual DbSet<Ranger> Rangers { get; set; }
        public virtual DbSet<Redeem_Reward> Redeem_Reward { get; set; }
        public virtual DbSet<Reserve> Reserves { get; set; }
        public virtual DbSet<Security_Company> Security_Company { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Tracking> Trackings { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Vehicle_Type> Vehicle_Type { get; set; }
        public virtual DbSet<Incident_Image> Incident_Image { get; set; }
        public virtual DbSet<Incident_Patrol> Incident_Patrol { get; set; }
        public virtual DbSet<Patrol_Asset> Patrol_Asset { get; set; }
        public virtual DbSet<Patrol_Marker> Patrol_Marker { get; set; }
        public virtual DbSet<Ranger_Reserve> Ranger_Reserve { get; set; }
        public virtual DbSet<Ranger_Vehicle> Ranger_Vehicle { get; set; }
    }
}
