//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Reward
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event_Reward()
        {
            this.Redeem_Reward = new HashSet<Redeem_Reward>();
            this.Redeem_Reward1 = new HashSet<Redeem_Reward>();
            this.Redeem_Reward2 = new HashSet<Redeem_Reward>();
            this.Redeem_Reward3 = new HashSet<Redeem_Reward>();
        }
    
        public int Event_Reward_ID { get; set; }
        public int Type_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Location { get; set; }
        public int Points { get; set; }
        public string Name { get; set; }
    
        public virtual Event_Type Event_Type { get; set; }
        public virtual Event_Type Event_Type1 { get; set; }
        public virtual Event_Type Event_Type2 { get; set; }
        public virtual Event_Type Event_Type3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redeem_Reward> Redeem_Reward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redeem_Reward> Redeem_Reward1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redeem_Reward> Redeem_Reward2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redeem_Reward> Redeem_Reward3 { get; set; }
    }
}
