//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_Patrol
    {
        public int Incident_ID { get; set; }
        public int Incident_Type_ID { get; set; }
        public int Incident_Level_ID { get; set; }
        public int Incident_Status_ID { get; set; }
        public int Patrol_Log_ID { get; set; }
        public int Patrol_Booking_ID { get; set; }
        public int Ranger_ID { get; set; }
        public int Reserve_ID { get; set; }
        public int Security_ID { get; set; }
        public decimal Lat { get; set; }
        public decimal Lng { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual Incident Incident { get; set; }
        public virtual Incident_Level Incident_Level { get; set; }
        public virtual Incident_Status Incident_Status { get; set; }
        public virtual Incident_Type Incident_Type { get; set; }
        public virtual Patrol_Booking Patrol_Booking { get; set; }
        public virtual Patrol_Log Patrol_Log { get; set; }
        public virtual Ranger Ranger { get; set; }
        public virtual Reserve Reserve { get; set; }
        public virtual Security_Company Security_Company { get; set; }
    }
}
