//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_Patrol
    {
        public int Incident_Patrol_ID { get; set; }
        public int Incident_ID { get; set; }
        public int Patrol_Log_ID { get; set; }
        public decimal Lat { get; set; }
        public decimal Lng { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Incident Incident { get; set; }
        public virtual Patrol_Log Patrol_Log { get; set; }
    }
}
