//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marker()
        {
            this.Patrol_Marker = new HashSet<Patrol_Marker>();
        }
    
        public int Marker_ID { get; set; }
        public decimal Longitude { get; set; }
        public decimal Lattitude { get; set; }
        public string Description { get; set; }
        public int Reserve_ID { get; set; }
        public int Marker_Type_ID { get; set; }
        public bool Status { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual Marker_Type Marker_Type { get; set; }
        public virtual Reserve Reserve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patrol_Marker> Patrol_Marker { get; set; }
    }
}
