//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Notification_ID { get; set; }
        public string Title { get; set; }
        public string Meassage { get; set; }
        public System.DateTime Date { get; set; }
        public int Ranger_ID { get; set; }
    
        public virtual Ranger Ranger { get; set; }
    }
}
