//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Line
    {
        public int Line_ID { get; set; }
        public Nullable<int> Asset_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Asset_Type_ID { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Asset_Type Asset_Type { get; set; }
        public virtual Order Order { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
