//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Reward
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Reward()
        {
            this.Redeem_Reward = new HashSet<Redeem_Reward>();
        }
    
        public int Product_Reward_ID { get; set; }
        public int Prod_ID { get; set; }
        public int Quantity { get; set; }
        public int Points { get; set; }
        public string Name { get; set; }
    
        public virtual Product_Type Product_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redeem_Reward> Redeem_Reward { get; set; }
    }
}
