//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Reward
    {
        public int Product_Reward_ID { get; set; }
        public int Prod_ID { get; set; }
        public int Quantity { get; set; }
        public int Points { get; set; }
        public string Name { get; set; }
    
        public virtual Product_Type Product_Type { get; set; }
    }
}
