//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranger_Reserve
    {
        public int Ranger_ID { get; set; }
        public int Reserve_ID { get; set; }
    
        public virtual Ranger Ranger { get; set; }
        public virtual Ranger Ranger1 { get; set; }
        public virtual Ranger Ranger2 { get; set; }
        public virtual Ranger Ranger3 { get; set; }
        public virtual Reserve Reserve { get; set; }
        public virtual Reserve Reserve1 { get; set; }
        public virtual Reserve Reserve2 { get; set; }
        public virtual Reserve Reserve3 { get; set; }
    }
}
