//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranger_Vehicle
    {
        public int Ranger_Vehicle_ID { get; set; }
        public int Vehicle_ID { get; set; }
        public int Ranger_ID { get; set; }
    
        public virtual Ranger Ranger { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
