//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ranger()
        {
            this.Cellphones = new HashSet<Cellphone>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Notifications = new HashSet<Notification>();
            this.Patrol_Booking = new HashSet<Patrol_Booking>();
            this.Patrol_Booking1 = new HashSet<Patrol_Booking>();
            this.Patrol_Log = new HashSet<Patrol_Log>();
            this.Incident_Patrol = new HashSet<Incident_Patrol>();
            this.Incident_Image = new HashSet<Incident_Image>();
            this.Patrol_Asset = new HashSet<Patrol_Asset>();
            this.Patrol_Marker = new HashSet<Patrol_Marker>();
            this.Ranger_Vehicle = new HashSet<Ranger_Vehicle>();
            this.Redeem_Reward = new HashSet<Redeem_Reward>();
            this.Trackings = new HashSet<Tracking>();
            this.Reserves = new HashSet<Reserve>();
        }
    
        public int Ranger_ID { get; set; }
        public string ID_Number { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Cell { get; set; }
        public int genderID { get; set; }
        public string Emerg_Name { get; set; }
        public string Emerg_Contact { get; set; }
        public byte[] Status { get; set; }
        public int User_Role_ID { get; set; }
        public int Medical_Aid_ID { get; set; }
        public int Points { get; set; }
        public string Blood_Type { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Organisation_ID { get; set; }
        public Nullable<int> OTP { get; set; }
        public byte[] Smartphone { get; set; }
        public int Access_ID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.DateTime> GUID_Exp { get; set; }
    
        public virtual Access_Level Access_Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cellphone> Cellphones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Medical_Aid Medical_Aid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Organisation Organisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patrol_Booking> Patrol_Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patrol_Booking> Patrol_Booking1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patrol_Log> Patrol_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident_Patrol> Incident_Patrol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident_Image> Incident_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patrol_Asset> Patrol_Asset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patrol_Marker> Patrol_Marker { get; set; }
        public virtual User_Role User_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ranger_Vehicle> Ranger_Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redeem_Reward> Redeem_Reward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracking> Trackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserve> Reserves { get; set; }
    }
}
