//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Role()
        {
            this.Rangers = new HashSet<Ranger>();
            this.Rangers1 = new HashSet<Ranger>();
            this.Rangers2 = new HashSet<Ranger>();
            this.Rangers3 = new HashSet<Ranger>();
        }
    
        public int User_Role_ID { get; set; }
        public Nullable<int> Access_ID { get; set; }
        public string Description { get; set; }
    
        public virtual Access_Level Access_Level { get; set; }
        public virtual Access_Level Access_Level1 { get; set; }
        public virtual Access_Level Access_Level2 { get; set; }
        public virtual Access_Level Access_Level3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ranger> Rangers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ranger> Rangers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ranger> Rangers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ranger> Rangers3 { get; set; }
    }
}
